### ISSUE TITLE
Use this endpoint in a real app

### ISSUE THREAD

**Issue by J-enke** [public-transport/transport.rest#11]
Hey,

can I use this endpoints in a real Android App? What is about a license?

Best regards.

**Comment by derhuerst** [comment]
Hey!

You can certainly use the `*.transport.rest` APIs in an Android app, as they're meant for public consumption.

But you shouldn't *rely* on them working; What that means specifically depends on your app: Is the data from `*.transport.rest` central to the app or just some side info? Is the app going to be well-known or not? etc.

Another option would be to fetch data directly from the underlying APIs directly, e.g. using [public-transport-enabler](https://github.com/schildbach/public-transport-enabler). There are pros and cons involved of course.

Regarding the licensing & legal situation, please read https://github.com/public-transport/transport.rest/issues/4#issuecomment-745636901.

Does that answer your questions?

**Comment by J-enke** [comment]
Hey derhuerst,

that is good, thank you for the answer. :)
