### ISSUE TITLE
Add poland-public-transport-api to transport.rest

### ISSUE THREAD

**Issue by konhi** [public-transport/transport.rest#13]
- [poland-public-transport-api](https://github.com/konhi/poland-public-transport-api) - https://poland-public-transport-api.azurewebsites.net/
- stable, hosted on Azure student's plan (I hope it doesn't have any hidden quotas! 😅), CORS enabled, no apikey or any ratelimits
- I am open for other contributors to extend it, or I'll do it by myself if I'll have interest in other regions - therefore I suggest **poland.transport.rest** as domain!

**Comment by derhuerst** [comment]
Such a neat project!

> [poland-public-transport-api](https://github.com/konhi/poland-public-transport-api) - https://poland-public-transport-api.azurewebsites.net/

The public instance is currently reported as being down. Are you planning to get it up online, or shall someone else host it?

> stable, hosted on Azure student's plan (I hope it doesn't have any hidden quotas! 😅), CORS enabled, no apikey or any ratelimits

✨

> I am open for other contributors to extend it, or I'll do it by myself if I'll have interest in other regions - therefore I suggest **poland.transport.rest** as domain!

Sure, let's do it. What DNS records to you need? A `CNAME` should be fine, right?

**Comment by konhi** [comment]
> Such a neat project!

Thanks! 💕 

> The public instance is currently reported as being down. Are you planning to get it up online, or shall someone else host it?

Well, it seems that Azure indeed had hidden quotas I didn't know about - $100, and somehow I used it in one week!
Sorry for that inconvenience, I'm going to let you know about DNS records and other details when I will manage to host it somewhere else!

**Comment by derhuerst** [comment]
There are probably better options, but [Vercel](https://vercel.com/pricing) and [Fly](https://fly.io/docs/about/pricing/) offer free plans. They suspend the server process if no traffic happens, but I guess that's fine for now.

**Comment by derhuerst** [comment]
Support with using which of the options?

[The instructions for using @juliuste's Kubernetes cluster](https://github.com/public-transport/infrastructure/tree/8e19c27855c2fd63f4f240d0fd7d8934a0279105/kubernetes#how-can-i-deploy-my-own-app) are quite technical, but you can try following them and ask for help either here or DM him.

**Comment by derhuerst** [comment]
@konhi ping 🙂 – Is there anything I can help you with regarding the deployment?

**Comment by derhuerst** [comment]
Let me know when it's ready to be mentioned at the `transport.rest` main page. Remember, all of these projects are personal and/or experimental projects, so it's perfectly fine to publish something half-done!

**Comment by derhuerst** [comment]
> I think it would be best if it points only to docs page, because `*.workers.dev` domain can change, or there can be many instances of this API.

It would be cool to have the actual API available via `poland.transport.rest` (or a subdomain of that), so that you can easily write scripts using the API, but if there's no stable domain for the Cloudflare Worker, then hosting the docs at `poland.transport.rest` is the best we can do.

> Docs page is available at http://konhi.github.io/poland-public-transport-api/. It uses GitHub pages, so [this link](https://docs.github.com/articles/using-a-custom-domain-with-github-pages/) might be useful. If I could help somehow, let me know!

I have configured a `CNAME` record for `poland.transport.rest`, pointing to to `kochi.github.io`. It seems like you have already configured GitHub to use this custom domain, so things should be working soon, right?

**Comment by derhuerst** [comment]
You can also make sure [to enforce HTTPS with the GitHub Page](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site).

**Comment by konhi** [comment]
> It would be cool to have the actual API available via poland.transport.rest (or a subdomain of that), so that you can easily write scripts using the API, but if there's no stable domain for the Cloudflare Worker, then hosting the docs at poland.transport.rest is the best we can do.

Definitely! It might be possible in the future, I will make sure to let you know in that case.

> I have configured a CNAME record for poland.transport.rest, pointing to to kochi.github.io. It seems like you have already configured GitHub to use this custom domain, so things should be working soon, right?

Awesome! Everything works perfectly! ✨
Could you please add `poland.transport.rest` to main website?
