### ISSUE TITLE
Geen data meer vanaf v6.db.transport.rest

### ISSUE THREAD

**Issue by Thijs053** [public-transport/transport.rest#24]
I no longer receive any data from v6.db.transport.rest, I receive a timeout message. At the departure times, and journey planner.

**Comment by marl0nx** [comment]
You may check the new id format. It is different now

**Comment by Thijs053** [comment]
I solved the problem with the data. But indeed the complete ride data can no longer be received due to the new ID's. 
I'm surprised it doesn't work anymore. Especially since the call has not been modified. 1| is also no longer available at all (this is why this entire API was created)

----
?id=2|#VN#1#ST#1718241941#PI#0#ZI#701110#TA#0#DA#160624#1S#5100005#1T#1834#LS#5100172#LT#2127#PU#80#RT#1#CA#IC#ZE#5124#ZB#IC%20 5124#PC#1#FR#5100005#FT#1834#TO#5100172#TT#2127#

**Comment by derhuerst** [comment]
Closing, as v6.db.transport.rest should be running again. Please re-open if you encounter issues (beyond a short "hiccup" of a few minutes).

Please keep in mind that the DB HAFAS API behind v6.db.transport.rest [is currently not working reliably](https://matrix.to/#/!fGsJOaXhgnTCFCghEl:matrix.org/$Af-pOVmexMHJ9b5YYtV2ThMl5loSI0oY9YaPhdP3GNU?via=matrix.org&via=kde.org&via=tchncs.de).

**Comment by derhuerst** [comment]
(We cannot do anything about the format and/or structure of the trip/journey IDs though, we pass them through from the underlying DB HAFAS API.)
