### ISSUE TITLE
Problems receiving data (You still)

### ISSUE THREAD

**Issue by Thijs053** [public-transport/transport.rest#26]
I have now adjusted the code (Ritdata) to the new call. And still I don't understand anything. This is starting to become very annoying (Always the same codes. and refusing APIs. It doesn't want that way (id=2%7C%23VN%231%23ST%231719862992%23PI%230%23ZI%231382522%23TA%230%23DA%2340724 %231S%238000098%231T%231549%23LS%238700014%23LT%232005%23PU%2380%23RT%231%23CA%23THA%23ZE%239474%23ZB%23EST%209474%23PC%230%23FR%2380 00098%23FT%231549 %23TO%238700014%23TT%232005%23), But also like this (2|#VN#1#ST#1719862992#PI#0#ZI#28068#TA#3#DA#40724#1S#585960#1T#1705 #LS#267053#LT#1832#PU#80#RT#1#CA#Bus#ZE#11#ZB#Bus 11#PC#5#FR#585960#FT#1705#TO#267053#TT#1832# ) refuses everything. This doesn't really seem to be the intention. I am slowly starting to see this as an error that cannot be repaired by the API data provider and if this does not work better, I plan to take it offline immediately. to get!

If a code ID does not work, you should not release it via the API.

**Comment by derhuerst** [comment]
I cannot control IDs that the API outputs, the API is merely a wrapper around the HAFAS API run by third parties.
