### ISSUE TITLE
Error 503 since at least 8 August 2024 (v6.bvg.transport.rest)

### ISSUE THREAD

**Issue by PaulOxxx1** [public-transport/transport.rest#27]
In the last couple of weeks I was not able to use the [v6.bvg.transport.rest](https://v6.bvg.transport.rest/) API at all, due to error 503 returned from all endpoints. This is probably related to https://github.com/public-transport/transport.rest/issues/25 .

@derhuerst If there is any way to support the resolution of this issue, let me know (because I'm assuming it is related to the deployment of the service, not the code per se).

**Steps to reproduce:**
- [OpenAPI playground](https://petstore.swagger.io/?url=https%3A%2F%2Fv6.bvg.transport.rest%2F.well-known%2Fservice-desc%0A) does not open:
  ![Screenshot 2024-08-16 at 10 31 19](https://github.com/user-attachments/assets/6d07edfc-db06-406b-b166-d6b64d041a88)
- via curl:
  ````bash
  ▶ curl -X 'GET' 'https://v6.bvg.transport.rest/locations?query=alex' -I  
  HTTP/2 503 
  alt-svc: h3=":443"; ma=2592000
  ratelimit-policy: 60; w=60
  server: Caddy
  content-length: 0
  date: Fri, 16 Aug 2024 08:32:08 GMT
  ````

**Comment by PaulOxxx1** [comment]
This is a duplicate of https://github.com/derhuerst/bvg-rest/issues/23

**Comment by PaulOxxx1** [comment]
I stumbled upon the workaround in https://github.com/derhuerst/bvg-rest/issues/22 , and replaced the URL in my service with https://v6.vbb.transport.rest, which fixes the issue for me.

**Comment by derhuerst** [comment]
Closing for now. (It's likely that `v6.bvg.transport.rest` was actually down, but it's cumbersome to debug retroactively.)

Please re-open if this happens again.
