### ISSUE TITLE
v6.vbb.transport.rest cert expired

### ISSUE THREAD

**Issue by krono** [public-transport/transport.rest#29]
The Let's encrypt cert of `v6.vbb.transport.rest` has expired:

```
% curl -kv https://v6.vbb.transport.rest
* Host v6.vbb.transport.rest:443 was resolved.
* IPv6: 2a01:4f8:c012:91b7::
* IPv4: 162.55.47.160
*   Trying [2a01:4f8:c012:91b7::]:443...
*   Trying 162.55.47.160:443...
* Connected to v6.vbb.transport.rest (162.55.47.160) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=v6.vbb.transport.rest
*  start date: Aug 10 01:52:03 2024 GMT
*  expire date: Nov  8 01:52:02 2024 GMT
*  issuer: C=US; O=Let's Encrypt; CN=E5
```

(Hope this is the right place to report :) )

**Comment by derhuerst** [comment]
Thanks for reporting!

Due to a – seemingly unsolved [1](https://caddy.community/t/unable-to-start-unexpected-end-of-json-input/25273) [2](https://caddy.community/t/caddy-is-not-starting-up/24565) [3](https://github.com/netbirdio/netbird/issues/2654) – bug in caddy, it is unable to obtain new SSL certificates.

**Comment by derhuerst** [comment]
I think I have solved the issue for now by deleting Caddy's data directory and restarting it.

Let me know if there are any issues again.

**Comment by krono** [comment]
Just after you closed, the endpoint worked well for a bit.
Sadly, it just times out at the moment for _any_ request :(

**Comment by derhuerst** [comment]
Please provide more details how you checked:
- URL(s) you tried, but ideally a `curl` (or other tool) snippet
- IPv4 vs IPv6
- how often you tried over which time span

**Comment by krono** [comment]
Hey,

* I tried on that day (5 days ago) 
* The command was `curl -v https://v6.vbb.transport.rest`
* IPv4 and (on a remote machine) IPv6
* I tried ~10 times on that day.

It seems to have recovered not, tho
