### ISSUE TITLE
v6.db.transport.rest (and other similar endpoints) is down

### ISSUE THREAD

**Issue by howardosborne** [public-transport/transport.rest#32]
Hi, the endpoint for v6.db.transport.rest is down - can I help in some way? thanks
https://stats.uptimerobot.com/57wNLs39M

**Comment by traines-source** [comment]
Thanks for reporting, should be up again. Sorry, this time some IPv4 issue that I don't fully understand yet though. And we'll better need to monitor the monitoring ;)

**Comment by howardosborne** [comment]
Great thanks

**Comment by howardosborne** [comment]
Hi, I think it's down again.

**Comment by traines-source** [comment]
See #34
