### ISSUE TITLE
BVG documentation inacurracy in description

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [public-transport/transport.rest#8]
## Description

Taking a look at https://v5.bvg.transport.rest/, it states that:

> Essentially, it returns whatever data the VBB app shows, including realtime delays and disruptions.

Which is the same as the description of https://v5.vbb.transport.rest/ states.

---

I think this should really state that "[..] it returns whatever data [the BVG app] shows [...]" instead of the VBB app.

### Pull request

I would have loved to open a PR for this, but I was not able to find the index of https://v5.bvg.transport.rest/ anywhere on GitHub. In general, I would say that the many repos in https://github.com/orgs/public-transport and https://github.com/derhuerst should be squashed into fewer [monorepos](https://en.wikipedia.org/wiki/Monorepo) for better searchability and maintainability ❤️ 

### Documentation

I have not been able to find it so far, so I would also add that it would be super useful for the doc pages to explain differences between the APIs. Right now, it is not immediately clear to me what the differences between the BVG and VBB APIs are.

**Comment by derhuerst** [comment]
> I think this should really state that "[..] it returns whatever data [the BVG app] shows [...]" instead of the VBB app.

Good catch!
